# -*- coding: utf-8 -*-
"""TUPLE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjOpmjhcZWlqHtRjnJF78hXfCyWKGnEv
"""

check=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")
answer=check.count("sunday")
print(answer)

check=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "saturday")
answer=check.count("january")
print(answer)

answer=check.index("saturday")
print(answer)

check=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")
print(check)
print(type(check))
print(len(check))

check=(("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday"))
print(check)
print(type(check))

chec=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")
print(chec[0])
print(chec[1])
print(chec[2])
print(chec[3])
print(chec[4])
print(chec[5])
print(chec[6])
print(type)

chec=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")

print(chec[-1])
print(chec[-2])
print(chec[-3])
print(chec[-4])
print(chec[-5])
print(chec[-6])
print(check[-7])

chec=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")
print(check[2:5])

print(check[2:])

print(check[:4])

check=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")
if "january" in check:
  print("yes")
else:
  print("No")

tuplevalue=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")
print(tuplevalue)

listvalue=list(tuplevalue)
listvalue[0]="sunday is holy day"

tuplevalue=tuple(listvalue)
print(tuplevalue)

tuplevalue=("chennai", "bengaluru", "delhi", "mumbai")
print(tuplevalue)

listvalue=list(tuplevalue)
listvalue.append("hyderabad")

tuplevalue=tuple(listvalue)
print(tuplevalue)

tuplevalue=("chennai", "bengaluru", "delhi", "mumbai")
print(tuplevalue)
setvalue=set(tuplevalue)
setvalue.add("hydearbad")

tuplevalue=tuple(setvalue)
print(tuplevalue)

tuplevalue1=("monday", "tuesday", "wednessday", "thursday", "friday")
tuplevalue2=("saturday", "sunday")


tuplevalue1+=tuplevalue2



print(tuplevalue1)

tuplevalue=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")

listvalue=list(tuplevalue)
listvalue.remove("sunday")

tuplevalue=tuple(listvalue)
print(tuplevalue)

tuplevalue=("chennai", "bengaluru", "delhi", "mumbai")
#(c1, c2, c3, c4)=tuplevalue
c1, *c2=tuplevalue

print(c1)
print(c2)

tuplevalue=("chennai", "bengaluru", "delhi", "mumbai")
for i in tuplevalue:
  print(i)

i=0
while i<len(tuplevalue):
  print(tuplevalue[i])
  i=i+1

tuplevalue=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")
for i in tuplevalue:
 print(i)

i=0
while i<len(tuplevalue):
  print(tuplevalue[i])
  i=i+1

tuplevalue1=("monday", "tuesday", "wednessday", "thursday", "friday")
tuplevalue2=("saturday", "sunday")

answer=tuplevalue1+tuplevalue2

print(answer)

tuplevalue=("sunday", "monday", "tuesday", "wednessday", "thursday", "friday", "sauturday")
answer=tuplevalue1*3
print(answer)

for i in range(len(tuplevalue)):
  print(tuplevalue[i])